apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.serviceName }}-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMulti
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.serviceName }}-storage
  hostPath:
    path: {{ .Values.dataPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.runServer }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.serviceName }}-pvc
spec:
  accessModes:
  - ReadWriteMulti
  storageClassName: {{ .Values.serviceName }}-storage
  resources:
    requests:
      storage: 20Gi
---
